# docker-compose.yml
services:
  forumcinemas-reporter:
    image: node:20-bookworm-slim
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npm install && 
        npm start
      "
