services:
  forumcinemas-reporter:
    build: .
    env_file: .env
    environment:
      GOMAXPROCS: 1
      WORKERS: 1
      DATA_DIR: /app/data
      REPORT_PATH: /app/index.html
    volumes:
      - .:/app
